name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Adjust this if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create .env file
        run: |
          echo "REACT_APP_COMPANY_DESCRIPTION=${{ secrets.REACT_APP_COMPANY_DESCRIPTION }}" >> .env
          echo "REACT_APP_REDIRECT_URL=${{ secrets.REACT_APP_REDIRECT_URL }}" >> .env
          echo "REACT_APP_COMPANY_NAME=${{ secrets.REACT_APP_COMPANY_NAME }}" >> .env
          echo "REACT_APP_COLLECTION_BANNER_DB=${{ secrets.REACT_APP_COLLECTION_BANNER_DB }}" >> .env
          echo "REACT_APP_COLLECTION_COUNTER_DB=${{ secrets.REACT_APP_COLLECTION_COUNTER_DB }}" >> .env
          echo "REACT_APP_COLLECTION_ABOUT_DB=${{ secrets.REACT_APP_COLLECTION_ABOUT_DB }}" >> .env
          echo "REACT_APP_COLLECTION_RIDE_DB=${{ secrets.REACT_APP_COLLECTION_RIDE_DB }}" >> .env
          echo "REACT_APP_COLLECTION_STORY_DB=${{ secrets.REACT_APP_COLLECTION_STORY_DB }}" >> .env
          echo "REACT_APP_COUNTER_DOCUMENT=${{ secrets.REACT_APP_COUNTER_DOCUMENT }}" >> .env
          echo "REACT_APP_ABOUT_DOCUMENT=${{ secrets.REACT_APP_ABOUT_DOCUMENT }}" >> .env
          echo "REACT_APP_BANNER_CUSTOM_LIST_1=${{ secrets.REACT_APP_BANNER_CUSTOM_LIST_1 }}" >> .env
          echo "REACT_APP_BANNER_CUSTOM_LIST_2=${{ secrets.REACT_APP_BANNER_CUSTOM_LIST_2 }}" >> .env
          echo "REACT_APP_BANNER_CUSTOM_LIST_3=${{ secrets.REACT_APP_BANNER_CUSTOM_LIST_3 }}" >> .env
          echo "REACT_APP_BANNER_CUSTOM_LIST_4=${{ secrets.REACT_APP_BANNER_CUSTOM_LIST_4 }}" >> .env
          echo "REACT_APP_PENDING=${{ secrets.REACT_APP_PENDING }}" >> .env
          echo "REACT_APP_ACCEPT=${{ secrets.REACT_APP_ACCEPT }}" >> .env
          echo "REACT_APP_REJECT=${{ secrets.REACT_APP_REJECT }}" >> .env
          echo "REACT_APP_TELEGRAM_LINK=${{ secrets.REACT_APP_TELEGRAM_LINK }}" >> .env
          echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}" >> .env
          echo "REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}" >> .env
          echo "REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID }}" >> .env
          echo "REACT_APP_FIREBASE_MEASUREMENT_ID=${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID }}" >> .env

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
