name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - release

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install and build
        run: |
          npm i
          npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CYCLE_E5661 }}
          channelId: live
          projectId: cycle-e5661
        env:
          CI: false
          REACT_APP_COMPANY_DESCRIPTION: ${{ secrets.REACT_APP_COMPANY_DESCRIPTION }}
          REACT_APP_REDIRECT_URL: ${{ secrets.REACT_APP_REDIRECT_URL }}
          REACT_APP_COMPANY_NAME: ${{ secrets.REACT_APP_COMPANY_NAME }}
          REACT_APP_COLLECTION_BANNER_DB: ${{ secrets.REACT_APP_COLLECTION_BANNER_DB }}
          REACT_APP_COLLECTION_COUNTER_DB: ${{ secrets.REACT_APP_COLLECTION_COUNTER_DB }}
          REACT_APP_COLLECTION_ABOUT_DB: ${{ secrets.REACT_APP_COLLECTION_ABOUT_DB }}
          REACT_APP_COLLECTION_RIDE_DB: ${{ secrets.REACT_APP_COLLECTION_RIDE_DB }}
          REACT_APP_COLLECTION_STORY_DB: ${{ secrets.REACT_APP_COLLECTION_STORY_DB }}
          REACT_APP_COUNTER_DOCUMENT: ${{ secrets.REACT_APP_COUNTER_DOCUMENT }}
          REACT_APP_ABOUT_DOCUMENT: ${{ secrets.REACT_APP_ABOUT_DOCUMENT }}
          REACT_APP_BANNER_CUSTOM_LIST_1: ${{ secrets.REACT_APP_BANNER_CUSTOM_LIST_1 }}
          REACT_APP_BANNER_CUSTOM_LIST_2: ${{ secrets.REACT_APP_BANNER_CUSTOM_LIST_2 }}
          REACT_APP_BANNER_CUSTOM_LIST_3: ${{ secrets.REACT_APP_BANNER_CUSTOM_LIST_3 }}
          REACT_APP_BANNER_CUSTOM_LIST_4: ${{ secrets.REACT_APP_BANNER_CUSTOM_LIST_4 }}
          REACT_APP_PENDING: ${{ secrets.REACT_APP_PENDING }}
          REACT_APP_ACCEPT: ${{ secrets.REACT_APP_ACCEPT }}
          REACT_APP_REJECT: ${{ secrets.REACT_APP_REJECT }}
          REACT_APP_TELEGRAM_LINK: ${{ secrets.REACT_APP_TELEGRAM_LINK }}
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID }}

      - name: Print secrets
        run: |
          echo "REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
          echo "FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CYCLE_E5661 }}"
          echo "REACT_APP_COMPANY_DESCRIPTION: ${{ secrets.REACT_APP_COMPANY_DESCRIPTION }}"
          echo "REACT_APP_REDIRECT_URL: ${{ secrets.REACT_APP_REDIRECT_URL }}"
          echo "REACT_APP_COMPANY_NAME: $REACT_APP_COMPANY_NAME"
          echo "REACT_APP_COLLECTION_BANNER_DB: $REACT_APP_COLLECTION_BANNER_DB"
          echo "REACT_APP_COLLECTION_COUNTER_DB: $REACT_APP_COLLECTION_COUNTER_DB"
          echo "REACT_APP_COLLECTION_ABOUT_DB: $REACT_APP_COLLECTION_ABOUT_DB"
          echo "REACT_APP_COLLECTION_RIDE_DB: $REACT_APP_COLLECTION_RIDE_DB"
          echo "REACT_APP_COLLECTION_STORY_DB: $REACT_APP_COLLECTION_STORY_DB"
          echo "REACT_APP_COUNTER_DOCUMENT: $REACT_APP_COUNTER_DOCUMENT"
          echo "REACT_APP_ABOUT_DOCUMENT: $REACT_APP_ABOUT_DOCUMENT"
          echo "REACT_APP_BANNER_CUSTOM_LIST_1: $REACT_APP_BANNER_CUSTOM_LIST_1"
          echo "REACT_APP_BANNER_CUSTOM_LIST_2: $REACT_APP_BANNER_CUSTOM_LIST_2"
          echo "REACT_APP_BANNER_CUSTOM_LIST_3: $REACT_APP_BANNER_CUSTOM_LIST_3"
          echo "REACT_APP_BANNER_CUSTOM_LIST_4: $REACT_APP_BANNER_CUSTOM_LIST_4"
          echo "REACT_APP_PENDING: $REACT_APP_PENDING"
          echo "REACT_APP_ACCEPT: $REACT_APP_ACCEPT"
          echo "REACT_APP_REJECT: $REACT_APP_REJECT"
          echo "REACT_APP_TELEGRAM_LINK: $REACT_APP_TELEGRAM_LINK"
          echo "REACT_APP_FIREBASE_API_KEY: $REACT_APP_FIREBASE_API_KEY"
          echo "REACT_APP_FIREBASE_AUTH_DOMAIN: $REACT_APP_FIREBASE_AUTH_DOMAIN"
          echo "REACT_APP_FIREBASE_PROJECT_ID: $REACT_APP_FIREBASE_PROJECT_ID"
          echo "REACT_APP_FIREBASE_STORAGE_BUCKET: $REACT_APP_FIREBASE_STORAGE_BUCKET"
          echo "REACT_APP_FIREBASE_MESSAGING_SENDER_ID: $REACT_APP_FIREBASE_MESSAGING_SENDER_ID"
          echo "REACT_APP_FIREBASE_APP_ID: $REACT_APP_FIREBASE_APP_ID"
          echo "REACT_APP_FIREBASE_MEASUREMENT_ID: $REACT_APP_FIREBASE_MEASUREMENT_ID"
