name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - release

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install and build
        run: |
          npm i
          npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CYCLE_E5661 }}
          channelId: live
          projectId: cycle-e5661
        env:
          CI: false
          REACT_APP_COMPANY_DESCRIPTION: "Company description esdmef sjndsjkfsd fndkesdds dskjn dskjndskjdsnd jdnsksdfd ds sddsnkjdsf dn dsjknfdskjndd s"
          REACT_APP_REDIRECT_URL: "http://localhost:3000"
          REACT_APP_COMPANY_NAME: "Cycling"
          REACT_APP_COLLECTION_BANNER_DB: "BANNER"
          REACT_APP_COLLECTION_COUNTER_DB: "COUNTER"
          REACT_APP_COLLECTION_ABOUT_DB: "ABOUT"
          REACT_APP_COLLECTION_RIDE_DB: "RIDE"
          REACT_APP_COLLECTION_STORY_DB: "STORY"
          REACT_APP_COUNTER_DOCUMENT: "bXl0IhUXLQRm0sjp5tli"
          REACT_APP_ABOUT_DOCUMENT: "SKmzfSyvpqC2AmvOcdpw"
          REACT_APP_BANNER_CUSTOM_LIST_1: "https://www.shutterstock.com/shutterstock/photos/502862680/display_1500/stock-vector-vector-sports-web-banner-motivational-concept-the-silhouette-of-the-biker-mountain-biking-man-502862680.jpg"
          REACT_APP_BANNER_CUSTOM_LIST_2: "https://www.shutterstock.com/image-vector/vector-cyclist-silhouette-ride-on-600nw-2206396469.jpg"
          REACT_APP_BANNER_CUSTOM_LIST_3: "https://c8.alamy.com/comp/MMYEJM/bicycle-club-vector-illustration-concept-for-shirt-or-logo-print-stamp-or-tee-vintage-typography-design-with-cycling-gear-and-chain-silhouette-e-MMYEJM.jpg"
          REACT_APP_BANNER_CUSTOM_LIST_4: "https://www.shutterstock.com/image-photo/man-racing-cyclist-motion-on-600nw-1855937053.jpg"
          REACT_APP_PENDING: "0"
          REACT_APP_ACCEPT: "1"
          REACT_APP_REJECT: "2"
          REACT_APP_TELEGRAM_LINK: "https://t.me/+z64u59FEZlQ2ZDBl"
          REACT_APP_FIREBASE_API_KEY: "AIzaSyAMOgZj-HNEdEANoWZqD6thyK7waxJ2FpU"
          REACT_APP_FIREBASE_AUTH_DOMAIN: "cycle-e5661.firebaseapp.com"
          REACT_APP_FIREBASE_PROJECT_ID: "cycle-e5661"
          REACT_APP_FIREBASE_STORAGE_BUCKET: "cycle-e5661.appspot.com"
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: "763530731165"
          REACT_APP_FIREBASE_APP_ID: "1:763530731165:web:a12430deeb1ed674afbe74"
          REACT_APP_FIREBASE_MEASUREMENT_ID: "G-V45QBK2MT2"
